### ISSUE TITLE
[Bug]: Jenkins plugins compability issue

### ISSUE THREAD

**Issue by gaiksaya** [opensearch-project/opensearch-ci#106]
### Describe the bug

Suddenly (04/15/22 around 5PM PST)  plugins installations started failing with below error:
```
022-04-15 02:37:25.111+0000 [id=42]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Token Macro Plugin v270.v8c2ce50dc4fc (token-macro)
java.io.IOException: Failed to load: Token Macro Plugin (270.v8c2ce50dc4fc)
 - Jenkins (2.277.1) or higher required
        at hudson.PluginWrapper.resolvePluginDependencies(PluginWrapper.java:952)
        at hudson.PluginManager$2$1$1.run(PluginManager.java:549)
        at org.jvnet.hudson.reactor.TaskGraphBuilder$TaskImpl.run(TaskGraphBuilder.java:169)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:296)
        at jenkins.model.Jenkins$5.runTask(Jenkins.java:1131)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:214)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at jenkins.security.ImpersonatingExecutorService$1.run(ImpersonatingExecutorService.java:59)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
2022-04-15 02:37:25.112+0000 [id=42]    SEVERE  jenkins.InitReactorRunner$1#onTaskFailed: Failed Loading plugin Folders Plugin v6.714.v79e858ef76a_2 (cloudbees-folder)
java.io.IOException: Failed to load: Folders Plugin (6.714.v79e858ef76a_2)
 - Jenkins (2.277.1) or higher required
 ```

Also on UI seeing below:
![image](https://user-images.githubusercontent.com/61760125/163630508-390f52e4-3423-45a3-9667-7f56cc84cf32.png)

### To reproduce

Try deploying jenkins with this repo's code base. It throw error as above. 
Try installing without any plugins and then install plugins using plugin manager on UI, you will see above image error

### Expected behavior

Jenkins should install and deploy all plugins

### Additional context

Looks like a bug https://issues.jenkins.io/browse/JENKINS-44377?page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel but not sure why it suddenly started failing and not before

**Comment by gaiksaya** [comment]
Below are the list of plugins from https://github.com/opensearch-project/opensearch-ci/blob/main/lib/compute/jenkins-plugins.ts that are unable to install

branch-api
build-timeout
cloudbees-folder
config-file-provider
disable-github-multibranch-status
docker-workflow
durable-task
email-ext
ghprb
github-branch-source
github
gradle
ivy
job-dsl
jquery
ldap
managed-scripts
matrix-auth
maven-plugin
nodelabelparameter
ownership
pipeline-github-lib
pipeline-model-definition
postbuildscript
preSCMbuildstep
project-description-setter
role-strategy
s3
saml
scm-api
throttle-concurrents
token-macro
workflow-aggregator
workflow-basic-steps
workflow-cps-global-lib
workflow-cps
workflow-durable-task-step
workflow-multibranch

**Comment by gaiksaya** [comment]
Looks like version is not considered anymore while installing plugin:
Command used:
```
java -jar /jenkins-cli.jar -s http://localhost:8080 -auth admin:416c7f7e0e754708856e46ce13f3c18e install-plugin cloudbees-folder:6.688.vfc7a_a_69059e0 -restart
```

Manifest:
```
Manifest-Version: 1.0
Hudson-Version: 2.277.1
Plugin-Dependencies: credentials:2.6.1;resolution:=optional
Implementation-Title: cloudbees-folder
Long-Name: Folders Plugin
Implementation-Version: 6.714.v79e858ef76a_2
Group-Id: org.jenkins-ci.plugins
Minimum-Java-Version: 1.8
Plugin-License-Name: MIT
Specification-Title: This plugin allows users to create "folders" to o
 rganize jobs. Users can define custom taxonomies (like   by project t
 ype, organization type etc). Folders are nestable and you can define
 views within folders. Maintained by CloudBees, Inc.
Plugin-ScmUrl: https://github.com/jenkinsci/cloudbees-folder-plugin
Plugin-Version: 6.714.v79e858ef76a_2
Jenkins-Version: 2.277.1
Url: https://github.com/jenkinsci/cloudbees-folder-plugin/
Short-Name: cloudbees-folder
Plugin-License-Url: https://opensource.org/licenses/MIT
Compatible-Since-Version: 5.2
Plugin-Developers:
Extension-Name: cloudbees-folder
Build-Jdk-Spec: 1.8
Created-By: Maven Archiver 3.5.2
```

**Comment by gaiksaya** [comment]
Another example:

```
[root@ip-172-31-17-4]# java -jar ~/jenkins-cli.jar -s http://localhost:8080 -auth admin:<fake> install-plugin branch-api:2.6.2 -restart
Installing branch-api:2.6.2 from update center
```
```
[root@ip-172-31-17-4 META-INF]# cat MANIFEST.MF
Manifest-Version: 1.0
Archiver-Version: Plexus Archiver
Created-By: Apache Maven
Built-By: runner
Build-Jdk: 1.8.0_322
Extension-Name: branch-api
Specification-Title: This plugin provides an API for multiple branch b
 ased projects.
Implementation-Title: branch-api
Implementation-Version: 2.1044.v2c007e51b_87f
Group-Id: org.jenkins-ci.plugins
Short-Name: branch-api
Long-Name: Branch API Plugin
Url: https://github.com/jenkinsci/branch-api-plugin
Compatible-Since-Version: 2.0.0
Minimum-Java-Version: 1.8
Plugin-Version: 2.1044.v2c007e51b_87f
Hudson-Version: 2.277.1
Jenkins-Version: 2.277.1
Plugin-Dependencies: cloudbees-folder:6.16,scm-api:2.6.5
Plugin-Developers: Stephen Connolly:stephenconnolly:
Plugin-License-Name: The MIT license
Plugin-License-Url: https://opensource.org/licenses/MIT
Plugin-ScmUrl: http://github.com/jenkinsci/branch-api-plugin
```

**Comment by gaiksaya** [comment]
Created bug with jenkins: https://issues.jenkins.io/browse/JENKINS-68306 also working on alternate approach to deploy jenkins

**Comment by gaiksaya** [comment]
Got reponse from the above TT. Looks like the jenkins version (2.263.4) that was being used before is not supported via update center anymore to install plugins. 
```
In general, the Update Center supports Jenkins core releases for 400 days after the Jenkins core release was shipped.
```
Looks like upgrading is the only option. In order to avoid future surprises like these, we will be using docker to set up jenkins. Keeping this issue open till then.

**Comment by gaiksaya** [comment]
What it would look like:
<img width="844" alt="image" src="https://user-images.githubusercontent.com/61760125/164464738-94eddeef-9fb9-436e-8832-847658ad181b.png">
