### ISSUE TITLE
[BUG] Windows Password never available on Jenkins after recent PRs

### ISSUE THREAD

**Issue by peterzhuamazon** [opensearch-project/opensearch-ci#297]
After #289 #291 #292 #293 #294 #295 #296, windows stuck on not able to boot and get password.

```
EC2 (Amazon_ec2_cloud) - jenkinsAgentNode-Jenkins-Agent-Windows2019-X64-C524xlarge-Single-Host
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.
Waiting for password to be available. Sleeping 10s.

```

**Comment by peterzhuamazon** [comment]
Seems like able to connect here:
```
Connecting to (10.0.101.113) with WinRM as Administrator
```

Wonder why it is stucking right now.

![image](https://github.com/opensearch-project/opensearch-ci/assets/65193828/03e6754a-95ac-4da9-a3b6-bc633c18a5b0)

**Comment by peterzhuamazon** [comment]
Right after attempt to connect it failed:
```
<pre id="out"><div>
</div><div>Waiting for WinRM to come up. Sleeping 10s.
</div><div>




<h2>HTTP ERROR 404 Not Found</h2>


URI: | /manage/computer/EC2%20%28Amazon%5Fec2%5Fcloud%29%20%2D%20jenkinsAgentNode%2DJenkins%2DAgent%2DWindows2019%2DX64%2DC524xlarge%2DSingle%2DHost%20%28i%2D019b97c099c560adc%29/logText/progressiveHtml
-- | --
404
Not Found
Stapler

</div></pre>
```

**Comment by peterzhuamazon** [comment]
Manually remove queue:
```
[hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6315, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6330, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6331, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6332, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6333, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6334, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6335, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6337, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6373, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6374, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6397, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6402, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6403, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6404, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6415, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6419, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6430, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6431, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6436, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6441, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6442, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6443, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6446, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6447, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6448, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6449, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6450, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6451, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6452, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6453, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6454, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6455, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6456, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6461, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6475, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6493, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6495, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6499, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6503, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6533, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6534, hudson.model.Queue$BlockedItem:org.jenkinsci.plugins.workflow.job.WorkflowJob@2ec5a7fc[gradle-check]:6535]

```

**Comment by peterzhuamazon** [comment]
Switch all the agents on build.ci.opensearch.org for windows back to 2023/05/19 versions.

**Comment by peterzhuamazon** [comment]
The above old ami confirms to connect with Jenkins
```

Waiting for password to be available. Sleeping 10s.
Connecting to (10.0.103.87) with WinRM as Administrator
Waiting for WinRM to come up. Sleeping 10s.
Waiting for WinRM to come up. Sleeping 10s.
Waiting for WinRM to come up. Sleeping 10s.
Connected with WinRM.
Creating tmp directory if it does not exist
Executing init script

C:\Users\Administrator>echo
ECHO is on.
init script ran successfully
remoting.jar sent remotely. Bootstrapping it
Launching via WinRM:java  -jar C:\Windows\Temp\remoting.jar -workDir C:/Users/Administrator/jenkins

```

Testing 2023/05/25 troubled AMI on personal account.

**Comment by peterzhuamazon** [comment]
Test running normal windows without any issues on connection, very weird.

**Comment by peterzhuamazon** [comment]
Possibly is the 300 seconds connection timeout is not enough on the new ami, will test next week on that.

**Comment by peterzhuamazon** [comment]
Seems like the loading time of the new AMI is longer even when manually logging in.

**Comment by peterzhuamazon** [comment]
Seems like stucking on this for a while:
![image](https://github.com/opensearch-project/opensearch-ci/assets/65193828/f45dc834-208c-4805-b3bc-05931c23785a)

**Comment by peterzhuamazon** [comment]
Takes 3 times longer just to get into Windows desktop.

**Comment by peterzhuamazon** [comment]
Seeing some errors:
```

ERROR: Timed out after 1007 seconds of waiting for winrm to be connected
com.amazonaws.AmazonClientException: Timed out after 1007 seconds of waiting for winrm to be connected
	at hudson.plugins.ec2.win.EC2WindowsLauncher.connectToWinRM(EC2WindowsLauncher.java:142)
	at hudson.plugins.ec2.win.EC2WindowsLauncher.launchScript(EC2WindowsLauncher.java:52)
	at hudson.plugins.ec2.EC2ComputerLauncher.launch(EC2ComputerLauncher.java:48)
	at hudson.slaves.SlaveComputer.lambda$_connect$0(SlaveComputer.java:298)
	at jenkins.util.ContextResettingExecutorService$2.call(ContextResettingExecutorService.java:46)
	at jenkins.security.ImpersonatingExecutorService$2.call(ImpersonatingExecutorService.java:80)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:829)

```

**Comment by peterzhuamazon** [comment]
After removing cypress the connection is ontime now.

**Comment by peterzhuamazon** [comment]
Since cypress can be cached by `npm install` during ftrepo run, and does have windows native exe anyway, I will remove the cypress installation from the script for now.

**Comment by peterzhuamazon** [comment]
The cypress is cached in `%localappdata%\Cache` (`\AppData\Local\Cache`) on windows by default which is different from `~/.cache` in nix*.

Seems related:
* https://learn.microsoft.com/en-us/troubleshoot/windows-server/performance/performance-issues-custom-default-user-profile

**Comment by peterzhuamazon** [comment]
Still not fully fix the old one takes 60*10seconds while the new one takes 90*10seconds or so.
Even if it login it will still error out due to timeout.

```
<pre id="out"><div>
Executing init script
</div><div>
C:\Users\Administrator&gt;echo
ECHO is on.
init script ran successfully
remoting.jar sent remotely. Bootstrapping it
Launching via WinRM:java  -jar C:\Windows\Temp\remoting.jar -workDir C:/Users/Administrator/jenkins
</div><div>&lt;===[JENKINS REMOTING CAPACITY]===&gt;Remoting version: 3107.v665000b_51092
Launcher: EC2WindowsLauncher
</div><div>Communication Protocol: Standard in/out
</div><div>This is a Windows agent
</div><div>




<h2>HTTP ERROR 404 Not Found</h2>


URI: | /manage/computer/EC2%20%28Amazon%5Fec2%5Fcloud%29%20%2D%20jenkinsAgentNode%2DJenkins%2DAgent%2DWindows2019%2DX64%2DC54xlarge%2DSingle%2DHost%20%28i%2D009b281124464ab3a%29/logText/progressiveHtml
-- | --
404
Not Found
Stapler

</div></pre>
```

**Comment by peterzhuamazon** [comment]
Seems like the delay is caused by adding `scoop cache rm --all` for some reason. Remove the line significantly boost the speed of startup.

**Comment by peterzhuamazon** [comment]
I combined the above steps and increase timeouts of boot up on Windows Agent, eventually get both it connected on Windows after 16-20min each boot, slightly longer than previous boot time of less than 15min.

Next time we can invest into pure server core windows, or even nano to improve time, we are currently using base version.
